# Libraries

In [3]:
from PIL import Image
import pandas as pd
import numpy as np

# Question 1

In [4]:
a = 12
print(a)
print()

a = 123
b = 345
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print()

string1 = "HelloHowAreYou"
print(string1.__len__())
print(len(string1))
print()

string2 = "234"
integer = int(string2)
print(integer)
print()



12

468
-222
42435
0.3565217391304348

14
14

234



# Question 2    

In [5]:
a = 435
b = 34256
a, b = b, a
print(f"a's value {a}")
print(f"b's value {b}")

a's value 34256
b's value 435


# Question 3

In [6]:
stringg = "I am a computer science student"
print(f"The first character is {stringg[0]}")
print(f"The characters from 3rd to 5th are => {stringg[3:6]}")
print(f"The characters from 3rd index onward are => {stringg[3:]}")

The first character is I
The characters from 3rd to 5th are => m a
The characters from 3rd index onward are => m a computer science student


# Question 4


In [7]:
list = [1, 2, 3, 4, 5, 6]
print(list)

print(f"items of list from index 3 onward => {list[3:]}")

list.insert(3, 100)
list.append(8)
print(f"items of the list after operations => {list}")

print(f"the 3rd ,4th and 5th items of the list => {list[3:6]}")

[1, 2, 3, 4, 5, 6]
items of list from index 3 onward => [4, 5, 6]
items of the list after operations => [1, 2, 3, 100, 4, 5, 6, 8]
the 3rd ,4th and 5th items of the list => [100, 4, 5]


# Question 5


In [8]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list1.extend(list2)
print(f"list1 after extending => {list1}")

list1 after extending => [1, 2, 3, 4, 5, 6]


# Question 6

In [9]:
tempList = list1.copy()
tuple = (1, "2", 3, list1)
print(f"tuple => {tuple}")

newTuple = ("programming", "programming", "programming")
print(f"New Tuple => {newTuple}")

tuple1 = (1, 2, 3, 4, 5)
tuple2 = (6, 7, 8, 9, 10)
tuple3 = tuple1 + tuple2
print(f"tuple3 => {tuple3}")

tuple => (1, '2', 3, [1, 2, 3, 4, 5, 6])
New Tuple => ('programming', 'programming', 'programming')
tuple3 => (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


# Question 7

In [10]:
person = { 'first_name': 'John','last_name': 'Doe','age':25,'favorite_colors': ['blue', 'green'],'active': True}
print(f"person => {person}")

print(f"Keys => {person.keys()}")
print(f"Values => {person.values()}")


index = 0;
for key in person.keys():
    if index == 1:
        print(f"the 2nd key is => {key}")
    if index == 2:
        break
    index += 1


person => {'first_name': 'John', 'last_name': 'Doe', 'age': 25, 'favorite_colors': ['blue', 'green'], 'active': True}
Keys => dict_keys(['first_name', 'last_name', 'age', 'favorite_colors', 'active'])
Values => dict_values(['John', 'Doe', 25, ['blue', 'green'], True])
the 2nd key is => last_name


# Question 8

In [11]:
inputVal = int(input("Enter a number: "))
print(f"inputVal => {inputVal}")
if inputVal%2 == 0:
    print("Even")
else:
    print("Odd")

inputVal => 45
Odd


# Question 9


In [12]:
list1 = [1, 2, 3, 4, 5, 6]
for item in list1:
    print(item)

1
2
3
4
5
6


# Question 10

In [13]:
listWithDuplicates = [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5]
uniqueList = []
for item in listWithDuplicates:
    if item not in uniqueList:
        uniqueList.append(item)

print(f"uniqueList => {uniqueList}")

uniqueSet = set(listWithDuplicates)
uniqueList2 = []
for item in uniqueSet:
    uniqueList2.append(item)
print(f"uniqueList using set => {uniqueList2}")

uniqueList => [1, 2, 3, 4, 5, 6]
uniqueList using set => [1, 2, 3, 4, 5, 6]


# Question 11

In [14]:
listOfLists = [[1,6,7,9],[7,9,3,5],[4,6,8,9]]
print(f"listOfLists => {listOfLists}")
array = np.array(listOfLists)

print(f"Dimentions using numpy => {array.ndim}")
print(f"Shape using numpy => {array.shape}")
print(f"Size using numpy => {array.size}")


listOfLists => [[1, 6, 7, 9], [7, 9, 3, 5], [4, 6, 8, 9]]
Dimentions using numpy => 2
Shape using numpy => (3, 4)
Size using numpy => 12


# Question 12

In [15]:
size = np.random.randint(1, 10)
randArr1 = np.random.randint(1, 100, size)
randArr2 = np.random.randint(1, 100, size)
print(f"randArr1 => {randArr1}")
print(f"randArr2 => {randArr2}")

randConcat = np.concatenate((randArr1, randArr2))
randArr1.sort()
randArr2.sort()
randArrAddition = randArr1 + randArr2
randArrSubtraction = randArr1 - randArr2
randArrMultiplication = randArr1 * randArr2
randArrDivision = randArr1 / randArr2

print(f"randConcat => {randConcat}")
print(f"Sorted randArr1 => {randArr1}")
print(f"Sorted randArr2 => {randArr2}")
print(f"randArrAddition => {randArrAddition}")
print(f"randArrSubtraction => {randArrSubtraction}")
print(f"randArrMultiplication => {randArrMultiplication}")
print(f"randArrDivision => {randArrDivision}")




randArr1 => [99 41 56 44 85 52 55]
randArr2 => [94 61 15 78 52 99 31]
randConcat => [99 41 56 44 85 52 55 94 61 15 78 52 99 31]
Sorted randArr1 => [41 44 52 55 56 85 99]
Sorted randArr2 => [15 31 52 61 78 94 99]
randArrAddition => [ 56  75 104 116 134 179 198]
randArrSubtraction => [ 26  13   0  -6 -22  -9   0]
randArrMultiplication => [ 615 1364 2704 3355 4368 7990 9801]
randArrDivision => [2.73333333 1.41935484 1.         0.90163934 0.71794872 0.90425532
 1.        ]


# Question 13

In [16]:
matrix = np.random.randint(1, 10, (4, 5))
print(f"matrix => \n {matrix}\n")

matrixTranspose = matrix.T
print(f"matrixTranspose =>\n{matrixTranspose}")

arrOfOnes = np.ones(10)
arrOfZeros = np.zeros(10)
arrOfFives = np.full(10, 5)
print(f"arrOfOnes =>\n{arrOfOnes}")
print(f"arrOfZeros =>\n{arrOfZeros}")
print(f"arrOfFives =>\n{arrOfFives}")

print(f"\nRandom Number between 0 and 1 is : {np.round(np.random.rand(), 3)}")

np.savetxt("matrix.txt", matrix, fmt='%d')
loadedMatrix = np.loadtxt("matrix.txt", dtype=int)
print(f"Loaded Matrix : \n{loadedMatrix}")


matrix => 
 [[4 4 9 6 6]
 [6 6 7 1 2]
 [4 7 2 2 7]
 [1 3 3 2 1]]

matrixTranspose =>
[[4 6 4 1]
 [4 6 7 3]
 [9 7 2 3]
 [6 1 2 2]
 [6 2 7 1]]
arrOfOnes =>
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
arrOfZeros =>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
arrOfFives =>
[5 5 5 5 5 5 5 5 5 5]

Random Number between 0 and 1 is : 0.355
Loaded Matrix : 
[[4 4 9 6 6]
 [6 6 7 1 2]
 [4 7 2 2 7]
 [1 3 3 2 1]]


## Question 14
Create a random matrix of 10 x 5 (where columns are the features and rows are the
patterns) and find the maximum and minimum values from each feature.

In [17]:
matrix = np.random.randint(1, 30, (10, 5))
print(f"matrix => \n {matrix}\n")

maxOfColumns = np.max(matrix, axis=0)
minOfColumns = np.min(matrix, axis=0)
print(f"maxOfColumns => {maxOfColumns}")
print(f"minOfColumns => {minOfColumns}")

matrix => 
 [[11 17 12 16  2]
 [ 2 21  5 10 16]
 [16  4 18 19 22]
 [17 29 24 18  7]
 [15 25 20  6 23]
 [19 21 22 25  6]
 [24 17 19 12 18]
 [17 24 16  3 17]
 [29 15 13 14 16]
 [15 17 25 11 24]]

maxOfColumns => [29 29 25 25 24]
minOfColumns => [2 4 5 3 2]


## Question 15
Create a random matrix of size 10 x 5 (where columns are the features and rows are the
patterns) and find the number of patterns having the same ith feature (i=1,2,...number of
features).

In [18]:
matrix = np.random.randint(1, 30, (10, 5))
print(f"matrix => \n {matrix}\n")

num_features = matrix.shape[1]

for i in range(num_features):
    column = matrix[:, i]
    unique, counts = np.unique(column, return_counts=True)
    print(f"\nFeature {i+1}:")
    for value, count in zip(unique, counts):
        print(f"Value {value} occurs {count} times")

    

matrix => 
 [[ 4 24 10 27 10]
 [19 11 18  3  3]
 [ 6 26  6 26  2]
 [16 25  7 27  9]
 [23 17 29  8  6]
 [ 1 16  7  5 17]
 [13 13 23 23 12]
 [28 18  1 21 19]
 [29 14 21 23 17]
 [ 5 27  6  6  8]]


Feature 1:
Value 1 occurs 1 times
Value 4 occurs 1 times
Value 5 occurs 1 times
Value 6 occurs 1 times
Value 13 occurs 1 times
Value 16 occurs 1 times
Value 19 occurs 1 times
Value 23 occurs 1 times
Value 28 occurs 1 times
Value 29 occurs 1 times

Feature 2:
Value 11 occurs 1 times
Value 13 occurs 1 times
Value 14 occurs 1 times
Value 16 occurs 1 times
Value 17 occurs 1 times
Value 18 occurs 1 times
Value 24 occurs 1 times
Value 25 occurs 1 times
Value 26 occurs 1 times
Value 27 occurs 1 times

Feature 3:
Value 1 occurs 1 times
Value 6 occurs 2 times
Value 7 occurs 2 times
Value 10 occurs 1 times
Value 18 occurs 1 times
Value 21 occurs 1 times
Value 23 occurs 1 times
Value 29 occurs 1 times

Feature 4:
Value 3 occurs 1 times
Value 5 occurs 1 times
Value 6 occurs 1 times
Value 8 occurs 1 times
V

## Question 16
Write a python program to read an image and save the image as a matrix to a .csv file
using pandas.

In [19]:
image = Image.open('/home/solomons/Codes/ML_Lab/PA1/image.jpg')
image = image.convert('RGB')
image_matrix = np.array(image)
reshaped_matrix = image_matrix.reshape(-1, 3)
df = pd.DataFrame(reshaped_matrix, columns=['Red', 'Green', 'Blue'])
df.to_csv('image_rgb_matrix.csv', index=False)

print("RGB image saved as matrix to 'image_rgb_matrix.csv'")


RGB image saved as matrix to 'image_rgb_matrix.csv'


## Question 17
Write a program to import excel data from the .csv file (generated in question 16) by
excluding the last row and last column.

In [20]:
data = pd.read_csv('image_rgb_matrix.csv')
data = data.iloc[:-1, :-1]
image_matrix = data.to_numpy()
print(f"Image Matrix from csv => {image_matrix}")

Image Matrix from csv => [[204 215]
 [202 213]
 [201 210]
 ...
 [186 201]
 [186 201]
 [190 205]]


## Question 18
Write a Pandas program to create today's date.

In [21]:
print(pd.to_datetime('today').date())

2024-08-01


## Question 19
Write a python program to read the dataset and print the number of
features, number of patterns, range of output available in the dataset. Write a program to
randomly split the dataset in X:Y ratio. Here, the values of X and Y are as follows (X+Y =
100% always):

a. X = 10:10:90 (i.e., initial: 10%, increment by 10%, maximum is 90%)
b. Y = 90:10:10 (i.e., initial: 90%, decrement by 10%, minimum is 10%)

In [22]:
data = pd.read_csv('salary_data.csv')
data = data.to_numpy()

num_features = data.shape[1]
num_patterns = data.shape[0]
print(f"Number of Features : {num_features}")
print(f"Number of Patterns : {num_patterns}")

output_column = data[:, -1]
output_range = (np.min(output_column), np.max(output_column))
print(f"Range of Output : {output_range}")

def splitter(data, x, y):
    size = data.shape[0]
    train_size = int(size * x)
    test_size = int(size * y)
    train_data = data[:train_size, :]
    test_data = data[train_size:train_size+test_size, :]
    return train_data, test_data

for i in range(1, 10):
    train_data, test_data = splitter(data, 0.1*i, 0.1*(10-i))
    print(f"Train Data Size : {train_data.shape[0]}")
    print(f"Test Data Size : {test_data.shape[0]}")
    print()


Number of Features : 2
Number of Patterns : 30
Range of Output : (np.float64(37731.0), np.float64(122391.0))
Train Data Size : 3
Test Data Size : 27

Train Data Size : 6
Test Data Size : 24

Train Data Size : 9
Test Data Size : 21

Train Data Size : 12
Test Data Size : 18

Train Data Size : 15
Test Data Size : 15

Train Data Size : 18
Test Data Size : 12

Train Data Size : 21
Test Data Size : 9

Train Data Size : 24
Test Data Size : 6

Train Data Size : 27
Test Data Size : 3



## Question 20
Write a program to calculate the row-wise,column-wise, and overall mean, median, mode,
and standard deviation of the dataset.


In [23]:
def row_wise_mode_fn():
    mode = []
    for row in data:
        unique, counts = np.unique(row, return_counts=True)
        mode.append(unique[np.argmax(counts)])
    return mode

def column_wise_mode_fn():
    mode = []
    for i in range(data.shape[1]):
        column = data[:, i]
        unique, counts = np.unique(column, return_counts=True)
        mode.append(unique[np.argmax(counts)])
    return mode

def overall_mode_fn():
    mode = []
    for i in range(data.shape[1]):
        column = data[:, i]
        unique, counts = np.unique(column, return_counts=True)
        mode.append(unique[np.argmax(counts)])
    unique, counts = np.unique(mode, return_counts=True)
    return unique[np.argmax(counts)]

row_wise_mean = np.mean(data, axis=1)
column_wise_mean = np.mean(data, axis=0)
overall_mean = np.mean(data)

row_wise_median = np.median(data, axis=1)
column_wise_median = np.median(data, axis=0)
overall_median = np.median(data)

row_wise_std = np.std(data, axis=1)
column_wise_std = np.std(data, axis=0)
overall_std = np.std(data)

row_wise_mode = row_wise_mode_fn()
column_wise_mode = column_wise_mode_fn()
overall_mode = overall_mode_fn()

print(f"Row-wise Mean: {', '.join(f'{val:.2f}' for val in row_wise_mean)}")
print(f"Column-wise Mean: {', '.join(f'{val:.2f}' for val in column_wise_mean)}")
print(f"Overall Mean: {overall_mean:.2f}")

print(f"Row-wise Median: {', '.join(f'{val:.2f}' for val in row_wise_median)}")
print(f"Column-wise Median: {', '.join(f'{val:.2f}' for val in column_wise_median)}")
print(f"Overall Median: {overall_median:.2f}")

print(f"Row-wise Standard Deviation: {', '.join(f'{val:.2f}' for val in row_wise_std)}")
print(f"Column-wise Standard Deviation: {', '.join(f'{val:.2f}' for val in column_wise_std)}")
print(f"Overall Standard Deviation: {overall_std:.2f}")

print(f"Row-wise Mode: {', '.join(f'{val:.2f}' for val in row_wise_mode)}")
print(f"Column-wise Mode: {', '.join(f'{val:.2f}' for val in column_wise_mode)}")
print(f"Overall Mode: {overall_mode:.2f}")

Row-wise Mean: 19672.05, 23103.15, 18866.25, 21763.50, 19946.60, 28322.45, 30076.50, 27224.10, 32224.10, 28596.35, 31610.95, 27899.00, 28480.50, 28542.55, 30557.75, 33971.45, 33017.05, 41546.65, 40684.45, 46973.00, 45872.40, 49140.05, 50654.95, 56910.10, 54719.85, 52795.50, 58489.25, 56322.30, 61200.65, 60941.25
Column-wise Mean: 5.31, 76003.00
Overall Mean: 38004.16
Row-wise Median: 19672.05, 23103.15, 18866.25, 21763.50, 19946.60, 28322.45, 30076.50, 27224.10, 32224.10, 28596.35, 31610.95, 27899.00, 28480.50, 28542.55, 30557.75, 33971.45, 33017.05, 41546.65, 40684.45, 46973.00, 45872.40, 49140.05, 50654.95, 56910.10, 54719.85, 52795.50, 58489.25, 56322.30, 61200.65, 60941.25
Column-wise Median: 4.70, 65237.00
Overall Median: 18870.75
Row-wise Standard Deviation: 19670.95, 23101.85, 18864.75, 21761.50, 19944.40, 28319.55, 30073.50, 27220.90, 32220.90, 28592.65, 31607.05, 27895.00, 28476.50, 28538.45, 30553.25, 33966.55, 33011.95, 41541.35, 40678.55, 46967.00, 45865.60, 49132.95, 50647